### ISSUE TITLE
README still mentions no dependencies

### ISSUE THREAD

**Issue by Ultimater** [novaksolutions/infusionsoft-php-sdk#170]
The README.md mentions
> **No dependencies.** If your server has PHP and cURL, then you are good to go!

Yet six months ago a dependency was added for handling UTF-8 characters:
https://github.com/novaksolutions/infusionsoft-php-sdk/commit/7364429ec48f93f4f06607cbc70a8d544b273570#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

**Comment by joeynovak** [comment]
That is a great point :)

I am usually a huge fan of no dependencies, it is still an option to pull the composer dependency in and make it so it doesn't require any, but I am not as sensitive to light-weight dependencies anymore.

What are your thoughts?  Pros and cons of having a dependency from your prespective?

**Comment by Ultimater** [comment]
@joeynovak I'm all for dependencies. This way there's less time spent re-creating the wheel.

Although some packages can run into conflicts such as a Guzzle 6 and Guzzle 7. If you use a package that relies on one and you use another package that relies on the other, boom, conflict. Generally this sort of thing can be resolved by picking package versions where the two Guzzle versions are compatible.
Does this prevent people from using Guzzle? Not at all. Look at laravel for example which updated their guzzle version with newer Laravel versions. People just create new releases of their packages when updating guzzle and the community does well.

I don't really see any cons with a dependency.
People would still be doing `composer install` either way.

But I'd sooner let them continue maintaining the package, and just update the README.

What wording to use on the README is beyond me though.

Could just copy-paste their one file:
https://github.com/neitanod/forceutf8/blob/master/src/ForceUTF8/Encoding.php

But I also like piggybacking off other's work.

So maybe just update the README.

**Comment by jchimene** [comment]
I solved this with Composer almost 6 months ago, and in the process found a long-standing bug in composer.json, submitted a PR => crickets. Thoughts?

**Comment by Ultimater** [comment]
> I solved this with Composer almost 6 months ago, and in the process found a long-standing bug in composer.json, submitted a PR => crickets. Thoughts?

What would you do different?

**Comment by jchimene** [comment]
> > I solved this with Composer almost 6 months ago, and in the process found a long-standing bug in composer.json, submitted a PR => crickets. Thoughts?
> 
> What would you do different?

Run  the update on my own servers as a proof of concept

**Comment by Ultimater** [comment]
@jchimene Ah, I didn't realize you were referring to a different repo.

I see your PR over there deletes a bunch of files and points to this repo for its files at dev-master.
I also see it uses `neitanod/forceutf8`. I don't see how your PR over there "solves" this issue, if anything it adds to the problem by switching over to more dependencies.

The issue is we're introducing dependencies, and the README over here says there's no dependencies.

So what course of action should be taken?
Merely update the README and remove the no dependencies mention?
Or do some sort of code refactoring, getting rid of dependencies, so the README is accurate?

**Comment by jchimene** [comment]
> @jchimene Ah, I didn't realize you were referring to a different repo.
> 
> I see your PR over there deletes a bunch of files and points to this repo for its files at dev-master.

Yes, the PR is really for the infusionsoft-sdk-for-wordpress, but it's relevant to this repository too. The PR was opened to address a few "complications" resulting from upstream (Joey) implementing `neitanod/forceutf8` in this SDK. My WordPress plugin uses the SDK, but does not bundle same; which implementation decision means any subsequent installs of the plugin would fail as the plugin does not implement composer. The deleted files happen because that silly-ass script attempts to move the composer stuff out of the plugin stuff destined for SVN. If you really want the gory details, I'll write a blog post...

> I also see it uses `neitanod/forceutf8`. I don't see how your PR over there "solves" this issue, if anything it adds to the problem by switching over to more dependencies.
If you want to continue using this SDK, you should switch to Composer. I did it for WordPress, and it's (crosses fingers) not that tough.

> The issue is we're introducing dependencies, and the README over here says there's no dependencies.

Yeah, that's an issue. Unfortunately....

> 
> So what course of action should be taken?

Migrate to composer, using the WordPress plugin as a proof of concept. As far as stand-alone goes, I think all you want is (1) implement the updated composer.json to correctly define the dependencies, and (2) remove the Novak autoloader from your script's bootup sequence.

> Merely update the README and remove the no dependencies mention?
Can't happen. I think Joey's committed to the `neitanod/forceutf8` stuff. It's the best solution anyway. It happens to require composer for WordPress, but that's a side issue. The (lack of correct) UTF-8 encoding in XMLRPC seems to have  been a nightmare from inception. Infusionsoft barely managed to convert to UTF-8 over the past few years. It's a system...


> Or do some sort of code refactoring, getting rid of dependencies, so the README is accurate?

That's your best answer. Remember, you don't need composer to install `neitanod/forceutf8` for either dev or production. It's a DIY operation, but hey - it's not my code! :)

There are other issues with XMLRPC, mostly that it will badly break under PHP 8 because each() moves to error from deprecated. The necessary updates to XMLRPC are lagging, too.

**Comment by joeynovak** [comment]
> The README.md mentions
> 
> > **No dependencies.** If your server has PHP and cURL, then you are good to go!
> 
> Yet six months ago a dependency was added for handling UTF-8 characters:
> [7364429#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34](https://github.com/novaksolutions/infusionsoft-php-sdk/commit/7364429ec48f93f4f06607cbc70a8d544b273570#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34)

Thanks for bringing this to my attention and your thoughts on dependencies.  They align with my thoughts as well. I'll update the readme :)

**Comment by jchimene** [comment]
I'm going to delete the other PR. It's obvious you either don't understand or don't want it.
