### ISSUE TITLE
Not updating contact just saving a new contact

### ISSUE THREAD

**Issue by kjphilips** [novaksolutions/infusionsoft-php-sdk#42]
Hi,

New to the SDK but it looks awesome. Following your video tutorial I was able to connect to my sandbox but it just kept creating a new contact.

I started with...
FirstName->'John';
LastName->'Doe';

save();

Then I added the Email->'john@doe.com';

ran it from terminal again and instead of updating that contact it created a new contact. 

Is this working as it should and should I be using an update function or do I have it set up wrong.

Some info on my setup...

I am running this straight from OS X and terminal, the file is in my Sites folder.

Thank you

**Comment by joeynovak** [comment]
Wow, sorry, this is an old ticket...  The sdk chooses to call insert or update based on if there is an Id on the contact object.

So just running your code again after adding email wouldn't work, since it's a new contact object again.  If you load a contact with $contact = new Infusionsoft_Contact($id), or get a contact from the data service, or set the $id manually, it will call save();
