### ISSUE TITLE
OAuth2 example returns 'Invalid redirect_uri'

### ISSUE THREAD

**Issue by Beejer** [novaksolutions/infusionsoft-php-sdk#72]
OAuth2 example returns fatal error 'Invalid redirect_uri' in OAuth2.php on line 85.

**Comment by jacobmhulse** [comment]
I just got the same issue when you posted.  Solved it by ensuring I was using HTTPS instead of HTTP for the value assigned to `Infusionsoft_OAuth2::$redirectUri`

Now I am getting a new error: `Didn't receive 200 OK from remote server. (HTTP/1.1 596 596) Attempted: 1 time(s). thrown in ...\Infusionsoft\App.php on line 157`

**Comment by Beejer** [comment]
HTTPS did not solve the issue for me.

**Comment by jnazareth1** [comment]
Hey @Beejer, I had the same issue 'invalid redirect_uri' and was able to fix it by making the following 2 changes:

1. Using HTTPS instead of HTTP for the value assigned to `Infusionsoft_OAuth2::$redirectUri` (as mentioned by jacobmhulse)

2. Removing any URL parameters from the $redirectURI by using either of the methods below: 

Typing the whole URL in manually:
`Infusionsoft_OAuth2::$redirectUri = "https://www.example.com/Oauth2.php"`

OR 

By cleaning the parameters using something like explode():
```
$cleanRedirectUri = explode('?', $_SERVER['REQUEST_URI'], 2);
Infusionsoft_OAuth2::$redirectUri = "https://$_SERVER[HTTP_HOST]" . $cleanRedirectUri[0];
```

I'm no pro so maybe someone can post a better way to do this but I thought I'd post it here if it may help.

**Comment by Beejer** [comment]
Hard-coding the redirect URI did the trick.  Thanks!

**Comment by jacobmhulse** [comment]
Sorry, I forgot to mention I also cleaned the URL just as @jnazareth1 suggested.
