### ISSUE TITLE
unable to retrieve Social links

### ISSUE THREAD

**Issue by prashantcs8** [novaksolutions/infusionsoft-php-sdk#86]
Twitter, Facebook, LinkedIn in general tab of contacts

**Comment by shawnhooper** [comment]
I don't have the link, since the community forums are offline right now, but this is actually a limitation of the Infusionsoft API.  The social fields just don't appear to be available except through the web interface.   

The recommendation in the forum post was to use a separate set of custom fields for this purpose and ignore the built-in ones in the general tab. Which really stinks.

**Comment by joeynovak** [comment]
Hey Shawn, thanks for jumping in and answering his question!
